declare module 'coffeescript' {
  interface CoffeeScript {
    compile(
      code: string,
      options?: {
        /**
         * if true, a source map will be generated; and instead of returning a string, compile will return an object of the form {js, v3SourceMap, sourceMap}.
         */
        sourceMap?: boolean;
        /**
         * if true, output the source map as a base64-encoded string in a comment at the bottom.
         */
        inlineMap?: boolean;
        /**
         * the filename to use for the source map. It can include a path (relative or absolute).
         */
        filename?: string;
        /**
         * if true, output without the top-level function safety wrapper.
         */
        bare?: boolean;
        /**
         * if true, output the Generated by CoffeeScript header.
         */
        header?: boolean;
        /**
         * if set, this must be an object with the options to pass to Babel. See Transpilation.
         */
        transpile?: any;
      }
    ): string;
  }
  export const CoffeeScript: CoffeeScript;
}
